services:
  frontend:
    container_name: frontend
    image: node:22
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    working_dir: /app/app
    command: sh -c "npm install && npm run dev && tail -f /dev/null"

